# generated by datamodel-codegen:
#   filename:  schema.json

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class NexusResearch(RootModel[Any]):
    root: Any = Field(
        ...,
        description="Shared types (TS single source of truth) → Pydantic via codegen",
        title="NexusResearch",
    )


class Collection(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    name: str
    icon: str
    count: float
    isSystem: bool


class DiffSegment(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["addition", "deletion", "unchanged"]
    text: str


class ModelInfo(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    name: str
    meta: str
    tags: list[str]
    isHot: bool


class StorageBreakdown(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    literature: float
    essays: float
    papers: float
    cache: float
    unit: Literal["GB", "MB"]


class DeleteLiteratureRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: float


class BulkLiteratureAction(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ids: list[float]
    action: Literal["delete", "markAsRead", "markAsUnread", "addTag", "removeTag", "addFavorite", "removeFavorite"]
    payload: str | None = None


class GenerateSummaryRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    literatureId: float
    modelId: str | None = None


class GenerateSummaryResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    summary: str
    modelUsed: str
    tokensUsed: float


class AiContext1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["literature"]
    literatureId: float


class AiContext2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["essay"]
    essayId: str


class AiContext3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["paper"]
    projectId: str
    activeFile: str | None = None


class AiContext4(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["reader"]
    literatureId: float
    currentPage: float


class AiContext(RootModel[AiContext1 | AiContext2 | AiContext3 | AiContext4]):
    root: AiContext1 | AiContext2 | AiContext3 | AiContext4 = Field(
        ..., description="AI 上下文 - 可辨识联合类型"
    )


class ProviderTestRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    providerId: str


class ProviderTestResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    success: bool
    latency: float
    error: str | None = None


class FetchModelsRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    providerId: str


class FetchModelsResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    models: list[ModelInfo]
    providerId: str


class InstallSkillRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    skillId: str


class UpdateSkillRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    skillId: str


class ConnectionTestResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    success: bool
    message: str
    latency: float | None = None


class Imported(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    literature: float
    essays: float
    papers: float
    settings: bool


class ImportDataResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    imported: Imported
    skipped: float
    errors: list[str]


class AnnotationType(RootModel[Any]):
    root: Any


class ChatRole(RootModel[Any]):
    root: Any


class CitationFormat(RootModel[Any]):
    root: Any


class CompatibilityType(RootModel[Any]):
    root: Any


class CompileStatus(RootModel[Any]):
    root: Any


class ConnectionStatus(RootModel[Any]):
    root: Any


class DiffAction(RootModel[Any]):
    root: Any


class EssayTag(RootModel[Any]):
    root: Any


class FileType(RootModel[Any]):
    root: Any


class HighlightColor(RootModel[Any]):
    root: Any


class ISODateString(RootModel[Any]):
    root: Any


class LatexTemplate(RootModel[Any]):
    root: Any


class ModuleType(RootModel[Any]):
    root: Any


class NoteTemplate(RootModel[Any]):
    root: Any


class OklchColor(RootModel[Any]):
    root: Any


class Omit3CEssay2C22id227C22createdAt227C22updatedAt223E(RootModel[Any]):
    root: Any


class PaginatedResponse3CEssay3E(RootModel[Any]):
    root: Any


class PaginatedResponse3CLiteratureListItem3E(RootModel[Any]):
    root: Any


class PaginatedResponse3CSkill3E(RootModel[Any]):
    root: Any


class PolishMode(RootModel[Any]):
    root: Any


class ProxyType(RootModel[Any]):
    root: Any


class ReadStatus(RootModel[Any]):
    root: Any


class SkillCategory(RootModel[Any]):
    root: Any


class SkillModule(RootModel[Any]):
    root: Any


class SkillStatus(RootModel[Any]):
    root: Any


class SortConfig3Cunknown3E(RootModel[Any]):
    root: Any


class Literature(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: float
    title: str
    authors: str
    journal: str
    year: float
    doi: str
    abstract: str
    aiSummary: str
    tags: list[str]
    isFavorite: bool
    readStatus: ReadStatus
    pdfUrl: str | None = None
    filePath: str | None = None


class LiteratureListItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    abstractPreview: str
    id: float
    title: str
    authors: str
    journal: str
    year: float
    tags: list[str]
    readStatus: ReadStatus
    isFavorite: bool


class Tag(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    name: str
    color: OklchColor
    count: float


class Annotation(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    type: AnnotationType
    color: HighlightColor
    page: float
    quotedText: str
    note: str
    createdAt: ISODateString


class ReadingNote(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    literatureId: float
    content: str
    template: NoteTemplate | None
    createdAt: ISODateString
    updatedAt: ISODateString


class ChatMessage(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    role: ChatRole
    content: str
    timestamp: ISODateString


class Essay(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    title: str
    content: str
    tag: EssayTag
    wordCount: float
    createdAt: ISODateString
    updatedAt: ISODateString


class AiEditSuggestion(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    segments: list[DiffSegment]
    accepted: bool | None


class FileNode(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    type: FileType
    children: list[FileNode] | None = None
    isActive: bool | None = None


class CompileLogEntry(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    level: Literal["info", "warn", "error", "success"]
    message: str
    timestamp: ISODateString


class Skill(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    name: str
    description: str
    icon: str
    category: list[SkillCategory]
    module: list[SkillModule]
    status: SkillStatus
    version: str
    latestVersion: str | None = None
    updateDescription: str | None = None


class SkillStats(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    skillId: str
    usageCount: float
    lastUsedAt: ISODateString | None
    status: Literal["running", "paused"]


class Provider(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    name: str
    icon: str
    description: str
    baseUrl: str
    apiKey: str
    compatibilityType: CompatibilityType
    connectionStatus: ConnectionStatus
    isDefault: bool


class ModuleModelAssignment(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    module: ModuleType
    modelId: str
    purpose: str


class ProxyConfig(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    enabled: bool
    type: ProxyType
    host: str
    port: float
    auth: str


class StorageInfo(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    used: str
    available: str
    breakdown: StorageBreakdown
    dataPath: str
    literatureCount: float
    essayCount: float
    paperCount: float


class LiteratureListRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    page: float
    pageSize: float
    sort: SortConfig3Cunknown3E | None = None
    search: str | None = None
    collectionId: str | None = None
    tagIds: list[str] | None = None
    readStatus: ReadStatus | None = None
    isFavorite: bool | None = None


class LiteratureListResponse(RootModel[PaginatedResponse3CLiteratureListItem3E]):
    root: PaginatedResponse3CLiteratureListItem3E = Field(..., description="文献列表响应")


class CreateLiteratureRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    importSource: Literal["doi", "pdf", "bibtex", "manual"] | None = None
    title: str
    authors: str
    journal: str
    year: float
    doi: str
    abstract: str
    tags: list[str]
    isFavorite: bool
    readStatus: ReadStatus
    pdfUrl: str | None = None
    filePath: str | None = None


class UpdateLiteratureRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: float
    title: str | None = None
    authors: str | None = None
    journal: str | None = None
    year: float | None = None
    tags: list[str] | None = None
    isFavorite: bool | None = None
    readStatus: ReadStatus | None = None


class GenerateCitationRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    literatureId: float
    format: CitationFormat


class EssayListRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    page: float
    pageSize: float
    sort: SortConfig3Cunknown3E | None = None
    search: str | None = None
    tag: EssayTag | None = None


class EssayListResponse(RootModel[PaginatedResponse3CEssay3E]):
    root: PaginatedResponse3CEssay3E = Field(..., description="随笔列表响应")


class CreateEssayRequest(RootModel[Omit3CEssay2C22id227C22createdAt227C22updatedAt223E]):
    root: Omit3CEssay2C22id227C22createdAt227C22updatedAt223E = Field(..., description="创建随笔请求")


class UpdateEssayRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    title: str | None = None
    content: str | None = None
    tag: EssayTag | None = None


class AiChatRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    messages: list[ChatMessage]
    context: AiContext
    modelId: str | None = None


class AiChatResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    message: ChatMessage
    modelUsed: str
    tokensUsed: float


class AiEditSuggestionResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    suggestion: AiEditSuggestion
    modelUsed: str


class ApplyEditRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    suggestionId: str
    action: DiffAction
    essayId: str


class PaperCompileRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    projectId: str
    template: LatexTemplate


class PaperPolishRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    projectId: str
    selectedText: str
    mode: PolishMode
    modelId: str | None = None


class PaperPolishResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    originalText: str
    polishedText: str
    mode: PolishMode


class SkillListRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    page: float
    pageSize: float
    sort: SortConfig3Cunknown3E | None = None
    search: str | None = None
    category: SkillCategory | None = None
    module: SkillModule | None = None
    status: SkillStatus | None = None


class SkillListResponse(RootModel[PaginatedResponse3CSkill3E]):
    root: PaginatedResponse3CSkill3E = Field(..., description="技能列表响应")


class CompileResult(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    status: CompileStatus
    pages: float
    fileSize: str
    logEntries: list[CompileLogEntry]
    errorCount: float
    warningCount: float


class InstalledSkill(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    stats: SkillStats
    id: str
    name: str
    description: str
    icon: str
    category: list[SkillCategory]
    module: list[SkillModule]
    status: SkillStatus
    version: str
    latestVersion: str | None = None
    updateDescription: str | None = None


class PaperCompileResponse(RootModel[CompileResult]):
    root: CompileResult = Field(..., description="论文编译响应")


class PaperProject(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    name: str
    fileTree: list[FileNode]
    template: LatexTemplate
    compileResult: CompileResult | None
    activeFile: str | None
    createdAt: ISODateString
    updatedAt: ISODateString


FileNode.model_rebuild()
